[package]
name = "corgi-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = { version = "0.14.1", features = ["wasm-bindgen"] }
eframe = "0.19.0"
rand = "0.8.5"
